<?php

namespace AtencionOnline\MensajeriaBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BuzonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuzonRepository extends EntityRepository
{
}