<?php

namespace AtencionOnline\LogicaBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClasificadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificadorRepository extends EntityRepository
{
    
}