<?php

namespace Raptor2\SyntarsusBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SecurityUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityUserRepository extends EntityRepository {

    public function getPageList($id, $start, $cant) {
        $query = $this->getEntityManager()->createQuery('SELECT u FROM Raptor2\SyntarsusBundle\Model\Entity\SecurityUser u WHERE u.idEstructure = ?1');
        $query->setParameter(1, $id);
        $query->setMaxResults($cant);
        $query->setFirstResult($start);
        return $query->getResult();
    }

    public function getPrivilegesUserPerRoute($user, $route) {

        $query = $this->getEntityManager()->createQuery(
                'SELECT p FROM '
                . 'Raptor2\SyntarsusBundle\Model\Entity\SecurityPrivilege p '
                . 'JOIN p.idRol r JOIN r.idUser u '
                . 'WHERE u.username=:username AND p.belongs=:route'
        );
        $query->setParameter('username', $user);
        $query->setParameter('route', $route);
        return $query->getResult();
    }

    public function getPrivilegesUserAll($user) {

        $query = $this->getEntityManager()->createQuery(
                'SELECT p FROM '
                . 'Raptor2\SyntarsusBundle\Model\Entity\SecurityPrivilege p '
                . 'JOIN p.idRol r JOIN r.idUser u '
                . 'WHERE u.username=:username AND(p.type=1 OR p.type=0)'
        );
        $query->setParameter('username', $user);

        return $query->getResult();
    }

    public function checkRoute($user, $route) {

        $query = $this->getEntityManager()->createQuery(
                'SELECT p FROM '
                . 'Raptor2\SyntarsusBundle\Model\Entity\SecurityPrivilege p '
                . 'JOIN p.idRol r JOIN r.idUser u '
                . 'WHERE u.username=:username AND p.route IN (:route)'
        );
        $query->setParameter('username', $user);
        $query->setParameter('route', $route);
        return $query->getResult();
    }
    
    public function findPrivilegesByRol($user, $roles) {

        $query = $this->getEntityManager()->createQuery(
                'SELECT p FROM '
                . 'Raptor2\SyntarsusBundle\Model\Entity\SecurityPrivilege p '
                . 'JOIN p.idRol r JOIN r.idUser u '
                . 'WHERE u.username=:username AND r.name IN (:roles)'
        );
        $query->setParameter('username', $user);
        $query->setParameter('roles', $roles);
        return $query->getResult();
    }

}
