<?php

namespace Raptor2\SyntarsusBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SecurityCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityCategoryRepository extends EntityRepository
{
}