<?php

namespace AtencionOnline\EncuestasBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AtenciononlineEncuestasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtenciononlineEncuestasRepository extends EntityRepository
{
}