<?php

namespace AtencionOnline\EncuestasBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AtenciononlineRespuestasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtenciononlineRespuestasRepository extends EntityRepository
{
}