<?php

namespace Proxies\__CG__\Raptor2\SyntarsusBundle\Model\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SecurityUser extends \Raptor2\SyntarsusBundle\Model\Entity\SecurityUser implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFullname($fullname)
    {
        $this->__load();
        return parent::setFullname($fullname);
    }

    public function getFullname()
    {
        $this->__load();
        return parent::getFullname();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setIcon($icon)
    {
        $this->__load();
        return parent::setIcon($icon);
    }

    public function getIcon()
    {
        $this->__load();
        return parent::getIcon();
    }

    public function setAttempts($attempts)
    {
        $this->__load();
        return parent::setAttempts($attempts);
    }

    public function getAttempts()
    {
        $this->__load();
        return parent::getAttempts();
    }

    public function setLastattempt($lastattempt)
    {
        $this->__load();
        return parent::setLastattempt($lastattempt);
    }

    public function getLastattempt()
    {
        $this->__load();
        return parent::getLastattempt();
    }

    public function setExtraData($extraData)
    {
        $this->__load();
        return parent::setExtraData($extraData);
    }

    public function getExtraData()
    {
        $this->__load();
        return parent::getExtraData();
    }

    public function addSecurityRol(\Raptor2\SyntarsusBundle\Model\Entity\SecurityRol $idRol)
    {
        $this->__load();
        return parent::addSecurityRol($idRol);
    }

    public function getIdRol()
    {
        $this->__load();
        return parent::getIdRol();
    }

    public function clearIdRol()
    {
        $this->__load();
        return parent::clearIdRol();
    }

    public function setIdEstructure(\Raptor2\SyntarsusBundle\Model\Entity\SecurityEstructure $idEstructure = NULL)
    {
        $this->__load();
        return parent::setIdEstructure($idEstructure);
    }

    public function getIdEstructure()
    {
        $this->__load();
        return parent::getIdEstructure();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fullname', 'username', 'email', 'password', 'state', 'icon', 'attempts', 'lastattempt', 'extraData', 'idRol', 'idEstructure');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}