<?php

namespace Proxies\__CG__\AtencionOnline\EncuestasBundle\Model\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AtenciononlinePreguntas extends \AtencionOnline\EncuestasBundle\Model\Entity\AtenciononlinePreguntas implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPregunta($pregunta)
    {
        $this->__load();
        return parent::setPregunta($pregunta);
    }

    public function getPregunta()
    {
        $this->__load();
        return parent::getPregunta();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setTipo($tipo)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function getTipo()
    {
        $this->__load();
        return parent::getTipo();
    }

    public function setOpcional($opcional)
    {
        $this->__load();
        return parent::setOpcional($opcional);
    }

    public function getOpcional()
    {
        $this->__load();
        return parent::getOpcional();
    }

    public function setIdEncuesta(\AtencionOnline\EncuestasBundle\Model\Entity\AtenciononlineEncuestas $idEncuesta = NULL)
    {
        $this->__load();
        return parent::setIdEncuesta($idEncuesta);
    }

    public function getIdEncuesta()
    {
        $this->__load();
        return parent::getIdEncuesta();
    }

    public function getCampos()
    {
        $this->__load();
        return parent::getCampos();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'pregunta', 'descripcion', 'tipo', 'opcional', 'idEncuesta', 'campos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}