<?php

namespace Proxies\__CG__\AtencionOnline\EncuestasBundle\Model\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AtenciononlineEncuestas extends \AtencionOnline\EncuestasBundle\Model\Entity\AtenciononlineEncuestas implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setTipo($tipo)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function getTipo()
    {
        $this->__load();
        return parent::getTipo();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setAnonimo($anonimo)
    {
        $this->__load();
        return parent::setAnonimo($anonimo);
    }

    public function getAnonimo()
    {
        $this->__load();
        return parent::getAnonimo();
    }

    public function setEnlace($enlace)
    {
        $this->__load();
        return parent::setEnlace($enlace);
    }

    public function getEnlace()
    {
        $this->__load();
        return parent::getEnlace();
    }

    public function setIdEstructura(\Raptor2\SyntarsusBundle\Model\Entity\SecurityEstructure $idEstructura = NULL)
    {
        $this->__load();
        return parent::setIdEstructura($idEstructura);
    }

    public function getIdEstructura()
    {
        $this->__load();
        return parent::getIdEstructura();
    }

    public function getPreguntas()
    {
        $this->__load();
        return parent::getPreguntas();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'tipo', 'estado', 'anonimo', 'enlace', 'preguntas', 'idEstructura');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}