<?php
 /**
  * THIS FILE IS GENERATED BY RAPTOR EXPORTER, TO EASLY UPLOAD THIS FILE AGAIN INTO THE 
  * DATABASE USE THE IMPORTER CLASS.
  * 
  * Generated January 17 2016 09:23:52 PM
  */
 
$create=array (
  0 => 'AtencionOnline\\EncuestasBundle\\Model\\Entity\\AtenciononlineCampos',
  1 => 'AtencionOnline\\EncuestasBundle\\Model\\Entity\\AtenciononlineEncuestas',
  2 => 'AtencionOnline\\EncuestasBundle\\Model\\Entity\\AtenciononlinePreguntas',
  3 => 'AtencionOnline\\EncuestasBundle\\Model\\Entity\\AtenciononlineRespuestas',
  4 => 'AtencionOnline\\EncuestasBundle\\Model\\Entity\\AtenciononlineUsuarios'
);
$data=array ();
