<?php
/**
 * Generated by Raptor
 * Define the Resources to minified
 */
namespace Util\RUXBundle\Compiler;
use Raptor\Asset\Resources;

class Compiler extends Resources{
    
    public function create() {
            
    }
}

?>