<?php
/**
 * Generated by Raptor
 * You can add a route prefix to this bundle
 * puting a @Route annotation to this class.
 * In this class you need to register your Bundle Aspects and your Rules for routes executions
 */
namespace AtencionOnline\UiComercialBundle;

use Raptor\Bundle\Annotations\Route;
use Raptor\Bundle\Bundle;
use Go\Core\AspectContainer;
use Raptor\Raptor;
use Raptor\Bundle\Route\RuleContainer;

/**
 * @Route("")
 */
class UiComercialBundle extends Bundle{

    public function registerBundleAspect(AspectContainer $appAspectContainer) {

    }

    public function entrance(Raptor $app) {

    }

    public function registerRouteRule(RuleContainer $ruleContainer) {
	 $ruleContainer->add('/ao/[\/\w]*', new Rule\Publish());
        \Util\RUXBundle\RUXBundle::protectRoute('/ao/[\/\w]*');
        
        \Util\RUXBundle\RUXBundle::setName('ao');
        \Util\RUXBundle\RUXBundle::addViewPlugin('rux_icon', '../../bundles/AtencionOnline/UiComercial/identity/title.png', '/ao/home');

        \Util\RUXBundle\RUXBundle::addViewPlugin('rux_name', "Bienvenido", '/ao/home');
        \Util\RUXBundle\RUXBundle::addViewPlugin('rux_sidebar_iconbase', "AtencionOnline/UiComercial/menu/", '/ao/home');
		
        \Util\RUXBundle\RUXBundle::addViewPlugin('rux_header', function($app){
            return $app->render('@UiComercialBundle/comercial.header.twig');
        }, '/ao/home');
        
        \Util\RUXBundle\RUXBundle::addViewPlugin('rux_script',function($app){
            return $app->render('@UiComercialBundle/inicio/script.html.twig');
        }, '/ao/home');
		
        \Util\RUXBundle\RUXBundle::addViewPlugin('rux_start', function($app) {
                    return $app->render('@UiComercialBundle/inicio/description.html.twig', array(
                                'lastweek' => ''
                    ));
                }, '/ao/home/description');
        $this->app->getSecurity()->getManager()->setLoginTemplate('@UiComercialBundle/login/index.html.twig');
    }

}

?>